# Generated by Django 2.2.6 on 2021-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задача'},
        ),
        migrations.AddField(
            model_name='category',
            name='priority_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
