# Generated by Django 2.2.6 on 2021-03-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210316_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
